SELECT * FROM INFORMATION_SCHEMA.TABLES;
SELECT * FROM MY_SCHEMA.USER_PASSWORD;
SELECT * FROM MY_SCHEMA.USER_PASSWORD_BASE64;
SELECT * FROM MY_SCHEMA.USER_PASSWORD_HASH;
SELECT * FROM MY_SCHEMA.USER_REVIEW;
